export const elementsQuestions = [
  {
    id: '1',
    desc: '「氫」的原子序為?',
    opt1: '1',
    opt2: '2',
    opt3: '3',
    opt4: '4',
    answer: 1,
  },
  {
    id: '2',
    desc: '「金」的原子符號為?',
    opt1: 'Cu',
    opt2: 'He',
    opt3: 'Au',
    opt4: 'Ag',
    answer: 3,
  },
  {
    id: '3',
    desc: '「Ar」屬於哪一類?',
    opt1: '鹵素',
    opt2: '類金屬',
    opt3: '過渡金屬',
    opt4: '惰性氣體',
    answer: 4,
  },
  {
    id: '4',
    desc: '「Cl」屬於哪一類?',
    opt1: '鹵素',
    opt2: '類金屬',
    opt3: '過渡金屬',
    opt4: '惰性氣體',
    answer: 1,
  },
  {
    id: '5',
    desc: '「Si」屬於哪一類?',
    opt1: '鹵素',
    opt2: '類金屬',
    opt3: '過渡金屬',
    opt4: '惰性氣體',
    answer: 2,
  },
  {
    id: '6',
    desc: '「鎂」的原子符號為?',
    opt1: 'Cu',
    opt2: 'Mg',
    opt3: 'Au',
    opt4: 'Ag',
    answer: 2,
  },
  {
    id: '7',
    desc: '「鉀」的原子符號為?',
    opt1: 'Cu',
    opt2: 'Mg',
    opt3: 'K',
    opt4: 'B',
    answer: 3,
  },
  {
    id: '8',
    desc: '「氮」的原子符號為?',
    opt1: 'I',
    opt2: 'N',
    opt3: 'K',
    opt4: 'B',
    answer: 2,
  },
  {
    id: '9',
    desc: '「碘」的原子符號為?',
    opt1: 'I',
    opt2: 'N',
    opt3: 'K',
    opt4: 'B',
    answer: 1,
  },
  {
    id: '10',
    desc: '「I」屬於哪一類?',
    opt1: '鹵素',
    opt2: '類金屬',
    opt3: '過渡金屬',
    opt4: '惰性氣體',
    answer: 1,
  },
  {
    id: '11',
    desc: '「B」屬於哪一類?',
    opt1: '鹵素',
    opt2: '類金屬',
    opt3: '過渡金屬',
    opt4: '惰性氣體',
    answer: 2,
  },
  {
    id: '12',
    desc: '「Zn」屬於哪一類?',
    opt1: '鹵素',
    opt2: '類金屬',
    opt3: '過渡金屬',
    opt4: '惰性氣體',
    answer: 3,
  },
  {
    id: '13',
    desc: '「Fe」屬於哪一類?',
    opt1: '鹵素',
    opt2: '類金屬',
    opt3: '過渡金屬',
    opt4: '惰性氣體',
    answer: 3,
  },
  {
    id: '14',
    desc: '「鈣」的原子符號為?',
    opt1: 'Cu',
    opt2: 'Ca',
    opt3: 'Au',
    opt4: 'Ag',
    answer: 2,
  },
  {
    id: '15',
    desc: '「鋁」的原子符號為?',
    opt1: 'Cu',
    opt2: 'Cs',
    opt3: 'Au',
    opt4: 'Al',
    answer: 4,
  },
];
